default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rain_app_development

test:
  <<: *default
  database: rain_app_test

production:
  <<: *default
  database: rain_app_production
  username: rain_app
  password: <%= ENV['RAIN_APP_DATABASE_PASSWORD'] %>
